### ISSUE TITLE
System.IO.FileNotFoundException: Cannot locate the file. (0x80070002)

### ISSUE THREAD

**Issue by Parvonse** [alexkleinwaechter/BeamNG_LevelCleanUp#41]
This occurs when I try to launch the .exe

**Comment by alexkleinwaechter** [comment]
The tool needs the Microsoft WebView2 Runtime to run properly. Its already installed on Windows 11 and newer versions of Windows 10. You can Download and install the Runtime from this Website:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/
Direct link to the installer:
https://go.microsoft.com/fwlink/p/?LinkId=2124703

Good luck :-)
